name: 'New Repo by Terraform CI/CD'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform_plan:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    outputs:
      plan_success: ${{ steps.check_changes.outputs.plan_success }}
    
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Format'
        run: terraform fmt

      - name: 'Terraform Plan'
        run: terraform plan -out=tfplan | tee plan_output.txt
        env:
          TF_VAR_github_token: ${{ secrets.TF_GITHUB_TOKEN }}

      - name: 'Check for Changes in Plan Output'
        id: check_changes
        run: |
          if grep -q "No changes. Infrastructure is up-to-date." plan_output.txt; then
            echo "::set-output name=plan_success::false"
            echo "No changes detected."
          else
            echo "::set-output name=plan_success::true"
            echo "Changes detected. Plan created successfully."
          fi

      - name: 'Upload Plan as Artifact'
        if: steps.check_changes.outputs.plan_success == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: tfplan
          path: tfplan

  terraform_apply:
    needs: terraform_plan
    if: needs.terraform_plan.outputs.plan_success == 'true' && github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment:
      name: 'dev'

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Download Plan Artifact'
        uses: actions/download-artifact@v2
        with:
          name: tfplan

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve tfplan
        env:
          TF_VAR_github_token: ${{ secrets.TF_GITHUB_TOKEN }}
