name: 'New Repo by Terraform CI/CD on pull request to develop'

on:
  pull_request:
    branches:
      - main
jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    outputs:
      plan_success: ${{ steps.check_changes.outputs.plan_success }}
    
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Format'
        run: terraform fmt

      - name: 'Terraform Plan'
        run: terraform plan
        env:
          TF_VAR_github_token: ${{ secrets.TF_GITHUB_TOKEN }}
